### PR TITLE
Ensure correct tools installation in goenv mode

### PR DESCRIPTION
**Pull request by faustind**
Tools will be installed in the appropriated directory when [goenv](https://github.com/syndbg/goenv) manages GOPATH.

I tried to make it work on Mac, Linux (Ubuntu), ~and Windows but I have no way of testing it on Windows~ 😅 

goenv doesn't seem to be supported on Windows.

### CODE REVIEW

**Comment by ray-x** [comment]
Hi, @faustind 
Thanks for the PR.
The only concern I have is `goenv_mode` will be called each time when go.nvim needs to execute a binary.
Could you add a local dict so the result will be stored locally?
e.g. in `utils.lua`
```lua
local installed = {}
...
if installed['gomodifytags'] then return true end
else
-- check if it installed
-- if installed
installed['gomodifytags'] = true
return true

```

**Comment by faustind** [comment]
@ray-x, 
Thanks for the suggestion. I cached the information about the installed tools in `utils.lua`

But the tests for gotags appear to randomly fail: I had the same jobs run on the same commit on my fork [here](https://github.com/faustind/go.nvim/pull/1/commits/94429679a53f933a9f857373d4243cfed2f293d5).

I suspect the 100ms wait for gotags action to take effect is not enough. So I bumped the wait time from 100ms to 500ms for `go_tags_spec.lua` in 8112fbc

**Review by ray-x — APPROVED** [review]
Thanks!

**Review by ray-x — APPROVED** [review]
Thanks!

**Comment by ray-x** [comment]
Timeout error might be caused by github actions. Sometimes there is more traffic.

**Pull request merged**
