### PR TITLE
fix:go unit test flag "-run" not "-r"

### LINKED ISSUE #301: unit test will be error
i notice
``` lua
  local run_flags = '-r'    // lua/go/gotest.lua:371 
...
  table.insert(cmd_args, '-r') // lua/go/gotest.lua:587
```
is not correct flag, i can't find -r in go test flag, and this will be error when i execute GoTestFunc and GoTestFile.
i can't confirm this flag, so i can't submit a PR. so i wonder these is a error or not

### PR DESCRIPTION
**Pull request by zhaogangang**
close #301

### CODE REVIEW

**Review by ray-x — COMMENTED** [review]
Thanks for the PR
this will break none floating test runner
if you disable floating term
GoTest -n 1  -> asyncmake -n 1
GoTest -C profile  -> asyncmake -C profile
GoTestFunc  -> asyncmake -r Funcname
Your fix will fix float term but will break async make runner.

**Comment by zhaogangang** [comment]
just like this?

**Comment by zhaogangang** [comment]
just like this?

**Comment by zhaogangang** [comment]
i am sorry without read lot of code, just modified according you saw

**Review by ray-x — APPROVED** [review]
thanks

**Pull request merged**
