### PR TITLE
fix(docs): fix command typo and duplicate

### PR DESCRIPTION
**Pull request by Nikola-Milovic**
In the Debug section Command table `GoBreakToggle` was mentioned twice, I just removed the duplicate

### CODE REVIEW

**Comment by Nikola-Milovic** [comment]
Now that I am looking over the other stuff, in this [section of the docs](https://github.com/ray-x/go.nvim#debug), the `GoBreakCondition` is supposed to be just `BreakCondition` ?

**Review by ray-x — APPROVED** [review]
thanks

**Comment by ray-x** [comment]
You are correct, it suppose to be `BreakCondition`

**Comment by ray-x** [comment]
Thanks, merged.

**Pull request merged**
