### PR TITLE
Replace print() with vim.notify()

### PR DESCRIPTION
**Pull request by rodrigc**

### CODE REVIEW

**Review by ray-x — APPROVED** [review]
Thanks, I was thinking of doing this for months.

**Comment by rodrigc** [comment]
Thanks for your support.

**Comment by rodrigc** [comment]
Have you used @rcarriga 's https://github.com/rcarriga/nvim-notify plugin?
This change looks good with that plugin

**Comment by ray-x** [comment]
Yes, it is a great plugin. I did not hook to it ATM. but with your changes, I should hook that.

**Pull request merged**
