### PR TITLE
fix require('go.util') error

### PR DESCRIPTION
**Pull request by nanozuki**
I'm sorry for that. I was confused by 'util' and 'utils' and make some typos. Now I fixed it. I tried these changed features, it works as before.

### CODE REVIEW

**Review by ray-x — APPROVED** [review]
Thanks for the quick fix!

**Comment by ray-x** [comment]
Did a quick test it looks good.

**Comment by nanozuki** [comment]
> Did a quick test it looks good.

I'm not familiar with Lua and saw some tests in the project. Is there some doc or script to run tests?

**Comment by ray-x** [comment]
The test is using nvim-lua/plenary.nvim  and Luadev (optional https://github.com/bfredl/nvim-luadev)

The document is : https://github.com/nvim-lua/plenary.nvim#plenarytest_harness

So far it is a manual run. I defined `test current file`  function as bellow:

```
_G.run_or_test = function(...)
  local ft = vim.bo.filetype
  local fn = vim.fn.expand("%")
  if fn == "[nvim-lua]" then
    return t("<Plug>(Luadev-Run)")
  end
  if ft == "lua" then
    local f = string.find(fn, "spec")
    if f == nil then
      -- let run lua test
      return t("<cmd>luafile %<CR>")
    end
    return t("<Plug>PlenaryTestFile")
  end
end
```

**Pull request merged**
