### PR TITLE
synchronous goimports

### PR DESCRIPTION
**Pull request by mateusz834**
When saving file while using auto saving (from README).
```
vim.api.nvim_exec([[ autocmd BufWritePre *.go :silent! lua require('go.format').goimport() ]], false)
```
The code is formatted, but not saved. (Formatting is executed after the file is saved)
Thie PR causes that goimports to be synchronous. (depending on lsp_fmt_async)

### CODE REVIEW

**Review by ray-x — COMMENTED** [review]
Sorry, vim.lsp.buf.formatting_sync is a deprecated function.
 vim.lsp.buf.format({async={true|false}}) should work in case of sync_format

**Comment by mateusz834** [comment]
I tested it and it seems like the `vim.lsp.buf.format({async = false})` does not work the same way as `formatting_sync`.
The `format({async = false})` still causes the same behaviour (save, then format).

**Comment by ray-x** [comment]
In that case, you might need to submit a PR for neovim. 
As formatting_sync is deprecated, there is no guarantee when this function will be deleted.

**Comment by mateusz834** [comment]
The vim.lsp.buf.format was polyfilled here, and that is why the async did not work.

**Review by ray-x — APPROVED** [review]

**Pull request merged**
